### ISSUE TITLE
能否灵活的设置请求的baseurl

### ISSUE THREAD

**Issue by wangran99** [LianjiaTech/retrofit-spring-boot-starter#10]
因为业务的复杂性，对请求的调用很少只对一个baseurl，可能有5个以上。能否不用拦截器，简单灵活的修改baseurl，谢谢。

**Comment by chentianming11** [comment]
你好，“对请求的调用很少只对一个baseurl，可能有5个以上。”，这个能举例说明一下吗？我暂时不太理解。
----------------------------------------
针对动态URL的场景，Retrofit支持使用`@Url`传入动态url参数，此时`baseurl`就不起作用了。
```java
    @GET
    Result<Person> getPerson(@Url String url, @Query("id") Long id);
```

**Comment by wangran99** [comment]
好的，明白了，谢谢。

**Comment by chentianming11** [comment]
嗯嗯，不过更推荐的方式还是不同baseUrl定义不同的接口。

**Comment by chentianming11** [comment]
关于“对请求的调用很少只对一个baseurl，可能有5个以上。”，我还是不太理解。可以加群讨论一下，我看看能不能在框架层面满足你的需求。群号：806714302

**Comment by chentianming11** [comment]
这种情况，可以认为是domain和端口会出现变化，但是请求本身的path是不变的。
后续解决的思路有两种：
1、第一种是设置baseUrl的时候不指定真实的域名和端口，而是会设置一个appName，然后在拦截器里面根据appName动态选择一个可用服务进行调用。
2、第二种是调用接口方法之前，支持通过一个静态方法设置appName和BaseUrl之间的映射，比如`RetrofitManager.put("sever1", "http://127.0.0.1:8080/api")`，然后执行的时候就是使用这个baseUrl执行调用。类似 https://github.com/JessYanCoding/RetrofitUrlManager 这种方式

老哥，之前你还提过，有根据真实的baseUrl不同，返回数据格式也会不同的情况。我也不太理解，因为一般情况下，如果是euraka的服务提供者，返回的数据格式应该是一样的，辛苦解答一下。

**Comment by wangran99** [comment]
好的👌我的意思是不同appName的调用返回的数据格式不同，比如有的返回json数据，有的返回xml数据，这样是不是需要自定义多个convert，怎么设置这些convert让他们在不同的appName时候对应不同的convert。另外你用的okhtttp是不是不是最新的版本

**Comment by wangran99** [comment]
baseUrl有支持微服务名动态更新的计划吗？

**Comment by chentianming11** [comment]
有计划做，但是时间会比较晚。近大半个月周末都有事情，短时间内没时间迭代了😂

**Comment by chentianming11** [comment]
2.1.4版本支持通过serviceId发起http调用了，具体可以看一下相关文档
