### ISSUE TITLE
Bug with `getDeclaringClass().getAnnotation(RetrofitClient.class)` eg ErrorDecoder / Degrade Interceptor

### ISSUE THREAD

**Issue by efemoney** [LianjiaTech/retrofit-spring-boot-starter#109]
First up, kudos on the new Interceptor based design!

Unfortunately, for any Interceptors that call `method.getDeclaringClass().getAnnotation(RetrofitClient.class)` there is a potential bug when using client interface heirarchies (affects [ErrorDecoder](https://github.com/LianjiaTech/retrofit-spring-boot-starter/blob/a110459dffeb96c3a6281d2a2db5e1574705fe2f/src/main/java/com/github/lianjiatech/retrofit/spring/boot/interceptor/ErrorDecoderInterceptor.java#L33) & Degrade Interceptors) eg.

```kt
interface Super {
  @GET("/super") fun getSuper()
}

@RetrofitClient(...)
interface Sub: Super
```

`getDeclaringClass()` will return `Super` but that is not the class with the `@RetrofitClient` annotation and will cause a NPE because the annotation will be `null`

**Comment by chentianming11** [comment]
Can you also add `@RetrofitClient` annotation to `Supper`? 

Taking the above example, if you want to define the outbound interface path accurately, `@GET` must be matched with `@RetrofitClient` to achieve this. If there is no `@RetrofitClient` on the `Supper`, just a `@GET` would also feel weird. The same goes for `Sub`.

**Comment by chentianming11** [comment]
Can you add `@RetrofitClient` on `Supper`? Limited by the Retrofit implementation, there is currently no way to get the `Sub` class.

**Comment by efemoney** [comment]
> Can you add @RetrofitClient on Supper?

Unfortunately no. `Sub` overrides some methods from `Super` to add caching plus some other utilities.

I understand that there is no way to get `Sub` in the interceptor. Maybe we can open an issue with https://github.com/square/retrofit to add the service instance to the invocation 🤔 

For now I am not feeling the effect of this because I have subclassed the ErrorDecoder and changed the implementation.

**Comment by chentianming11** [comment]
you're right, we can only wait for `Retrofit` to support service instance in `Invocation`. However, `Retrofit` has not been updated for over 1 year.

**Comment by efemoney** [comment]
The PR has been merged in Retrofit!

**Comment by chentianming11** [comment]
Versions 2.4.0 and 3.1.0 are already supported
