### ISSUE TITLE
Support all annotations as meta-annotations

### ISSUE THREAD

**Issue by efemoney** [LianjiaTech/retrofit-spring-boot-starter#110]
I do not see any reason against having annotations like `@RetrofitClient`, `@Resilience4jDegrade` etc be meta-annotations.

We can use Spring's [AnnotationUtils](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AnnotationUtils.html) or [AnnotatedElementUtils](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AnnotatedElementUtils.html) together with the [MergedAnnotations API](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/MergedAnnotation.html) to easily manage & support meta-annotations.

That way we can have for example
```kt
@RetrofitClient(baseUrl = "$shared-base-url")
annotation class MyBaseUrlClient

// With usage
@MyBaseUrlClient interface A { ... }
@MyBaseUrlClient interface B { ... }
```
and `A` & `B` will share the same `baseUrl`.

Or an even more advanced use case is to define common configuration and then let the use-site define the remaining configuration.
```kt
@Service
@RetrofitClient(baseUrl = "$my-base-url", errorDecoder = ...)
annotation class ServiceIdClient(
  @AliasFor(annotation = RetrofitClient::class, attribute = "serviceId")
  val value: String
)

// And use it like
@ServiceIdClient("service-a") interface A { ... }
@ServiceIdClient("service-b") interface B { ... }
```

**Comment by chentianming11** [comment]
> I do not see any reason against having annotations like `@RetrofitClient`, `@Resilience4jDegrade` etc be meta-annotations.
> 
> We can use Spring's [AnnotationUtils](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AnnotationUtils.html) or [AnnotatedElementUtils](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AnnotatedElementUtils.html) together with the [MergedAnnotations API](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/MergedAnnotation.html) to easily manage & support meta-annotations.
> 
> That way we can have for example
> 
> ```kotlin
> @RetrofitClient(baseUrl = "$shared-base-url")
> annotation class MyBaseUrlClient
> 
> // With usage
> @MyBaseUrlClient interface A { ... }
> @MyBaseUrlClient interface B { ... }
> ```
> 
> and `A` & `B` will share the same `baseUrl`.
> 
> Or an even more advanced use case is to define common configuration and then let the use-site define the remaining configuration.
> 
> ```kotlin
> @Service
> @RetrofitClient(baseUrl = "$my-base-url", errorDecoder = ...)
> annotation class ServiceIdClient(
>   @AliasFor(annotation = RetrofitClient::class, attribute = "serviceId")
>   val value: String
> )
> 
> // And use it like
> @ServiceIdClient("service-a") interface A { ... }
> @ServiceIdClient("service-b") interface B { ... }
> ```

Makes sense, I'll support the feature asap.

**Comment by chentianming11** [comment]
```
@RetrofitClient(baseUrl = "$shared-base-url")
annotation class MyBaseUrlClient

// With usage
@MyBaseUrlClient interface A { ... }
@MyBaseUrlClient interface B { ... }
```

`@MyBaseUrlClient`  also needs to add `@Retention`、`@Target`，like below：

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Documented
@Inherited
@RetrofitClient(baseUrl = "${test.baseUrl}")
@Logging(logLevel = LogLevel.WARN)
public @interface MyRetrofitClient {

    @AliasFor(annotation = RetrofitClient.class)
    Class<? extends Converter.Factory>[] converterFactories();

    @AliasFor(annotation = Logging.class)
    LogStrategy logStrategy();
}
```

**Comment by chentianming11** [comment]
I support the above issue via `AnnotatedElementUtils.findMergedAnnotation()`.

**Comment by chentianming11** [comment]
Version 2.3.2 is already supported

https://github.com/LianjiaTech/retrofit-spring-boot-starter/releases/tag/2.3.2
