### ISSUE TITLE
考虑支持 maxRequests、maxRequestsPerHost 的配置吗

### ISSUE THREAD

**Issue by daliandazi** [LianjiaTech/retrofit-spring-boot-starter#111]
内部服务之间用OKHTTP调用，默认的maxRequests、maxRequestsPerHost太小限制了并发量，生产环境对这2个参数做了调整后效果还是比较明显；retrofit-spring-boot-starter 虽然可以用代码自定义注入OkHttpClient并做很多自定义配置，但是不够优雅便捷。

**Comment by daliandazi** [comment]
在Dispatcher中设置，需要自定义初始化 Dispatcher，如下：
``` java
 int maxRequests = 100;
 ExecutorService dispatchExecutor = new ThreadPoolExecutor(5, maxRequests, 60, TimeUnit.SECONDS,
                new SynchronousQueue<>(), Util.threadFactory("OkHttp Dispatcher XXX", false), new ThreadPoolExecutor.DiscardPolicy());
        Dispatcher dispatcher = new Dispatcher(dispatchExecutor);
        dispatcher.setMaxRequests(maxRequests);
        dispatcher.setMaxRequestsPerHost(maxRequests);
```
Builder的dispatcher(dispatcher)方法传进去就行了。

**Comment by chentianming11** [comment]
https://github.com/LianjiaTech/retrofit-spring-boot-starter/releases/tag/2.3.3

2.3.3版本重构了自定义OkHttpClient属性。你这个需求可以自行注入支持了。具体看文档：
https://github.com/LianjiaTech/retrofit-spring-boot-starter#%E8%87%AA%E5%AE%9A%E4%B9%89OkHttpClient%E5%B1%9E%E6%80%A7
