### ISSUE TITLE
A bean with that name has already been defined in class path resource [com/github/lianjiatech/retrofit/spring/boot/config/RetrofitAutoConfiguration.class] and overriding is disabled.

### ISSUE THREAD

**Issue by ElanYoung** [LianjiaTech/retrofit-spring-boot-starter#113]
😂 有一个库的依赖和retrofit的日志拦截器的bean名字重复了

方便**The bean 'logInterceptor'**改为**loggingInterceptor**嘛

**Comment by chentianming11** [comment]
改名字也不是长久之计，你试试自行覆盖呢，加上如下bean配置。

```java
@Bean
    public LoggingInterceptor loggingInterceptor() {
        return new LoggingInterceptor(retrofitProperties.getGlobalLog());
    }
```

![image](https://user-images.githubusercontent.com/30620547/169936746-b918a59b-8346-4abd-8f92-8683b296629e.png)
亲测上面这样是可行的。

**Comment by ElanYoung** [comment]
> 

retrofitProperties 我自己定义嘛

**Comment by ElanYoung** [comment]
搞定了！我自定义配置覆盖了

**Comment by chentianming11** [comment]
> retrofitProperties 我自己定义嘛

直接注入即可。
