### ISSUE TITLE
baseUrl动态绑定

### ISSUE THREAD

**Issue by liuxuewang** [LianjiaTech/retrofit-spring-boot-starter#116]
应用场景：API接口相同，但提供API的服务地址不同
按现在的方式，好象只能按不同的服务提供地址，分别创建@RetrofitClient 
请问可以根据不同的请求来切换不同的baseUrl 进行API调用吗？
如果可以的话，请说一下解决方案

**Comment by chentianming11** [comment]
试试动态URL`@Url`能不能解决。

**Comment by chentianming11** [comment]
https://github.com/LianjiaTech/retrofit-spring-boot-starter/blob/master/README.md#%E5%8A%A8%E6%80%81url

**Comment by liuxuewang** [comment]
这个方式是可以解决，但是感觉不太友好
感谢您的回复
