### ISSUE TITLE
[Feature Request] Add decorator support （添加对装饰器模式的支持）

### ISSUE THREAD

**Issue by aboutZZ** [LianjiaTech/retrofit-spring-boot-starter#120]
有时，我们想对请求进行装饰。
比较经典的场景是请求验签，例如：支付宝请求接口要求对请求参数进行签名计算。

能否添加一个装饰器选项（例如，在`@RetrofitClient`注解中，传入装饰器class，执行`decorate`方法），这样我们在每次请求时无需关心签名问题，只需要关心业务逻辑即可。

**Comment by chentianming11** [comment]
目前通过拦截器也能解决这种问题吧？
