### ISSUE TITLE
增加 idea 语言注入支持

### ISSUE THREAD

**Issue by cn-src** [LianjiaTech/retrofit-spring-boot-starter#122]
给 RetrofitClient#baseUrl 标注上 @org.intellij.lang.annotations.Language("SpEL") 注解，能更好的支持 idea 提示功能。
其他地方类似。

**Comment by chentianming11** [comment]
感觉这样依赖太重了，使用者并不一定使用IDEA开发。

**Comment by aboutZZ** [comment]
依赖方式使用`provided`呢？
