### ISSUE TITLE
默认配置的类好像对baseUrl无效

### ISSUE THREAD

**Issue by 4color** [LianjiaTech/retrofit-spring-boot-starter#124]
@RetrofitClient(baseUrl = "${storge.url}"

@Data
@ConfigurationProperties(prefix = "storge")
public class StorgeClientProperties {

    private String url = "http://localhost:11010";

}

必须在配置文件里加参数才可以。

**Comment by chentianming11** [comment]
确实这样子的，因为底层是从`Environment`取值的。我理解下来，这种情况是不影响使用的。
