### ISSUE TITLE
Setting the client bean as primary should not be the default

### ISSUE THREAD

**Issue by efemoney** [LianjiaTech/retrofit-spring-boot-starter#132]
https://github.com/LianjiaTech/retrofit-spring-boot-starter/blob/e84924e65b28c8700591b81121bbb6aa795c8f13/src/main/java/com/github/lianjiatech/retrofit/spring/boot/core/ClassPathRetrofitClientScanner.java#L75

Within my project, I decorate the retrofit client bean (with caching for instance) and I mark the decorated one as primary

```kt
@Service @RetrofitClient(baseUrl = ...)
interface PlansClient : PlansApi

@Primary @Service
class PlansImpl(cache: Cache, private val client: PlansClient) : PlansApi by client {

  override suspend fun getRegion(regionId: RegionId) =
    cache.get("getRegion[$regionId]") { client.getRegion(regionId) }

  ...
}
```

Its an error because from version `2.3.8`, there is now two primary `PlansApi` 😢

**Comment by chentianming11** [comment]
ok，I deleted this line of code in version `2.3.9` 😓
