### ISSUE TITLE
@SentinelDegrade注解不生效

### ISSUE THREAD

**Issue by shelltea** [LianjiaTech/retrofit-spring-boot-starter#135]
1. 增加Sentinel依赖和配置，启动熔断降级功能；
```
        <dependency>
            <groupId>com.github.lianjiatech</groupId>
            <artifactId>retrofit-spring-boot-starter</artifactId>
            <version>2.3.9</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <version>1.8.3</version>
        </dependency>
```

```
retrofit.degrade.degrade-type = sentinel
```

2. 在接口上配置@SentinelDegrade注解，异常数超过1触发降级，如下：
```
@SentinelDegrade(grade = 2, count = 1)
@RetrofitClient(baseUrl = "https://api.com", connectTimeoutMs = 3000,
        fallback = ApiFallback.class, fallbackFactory = ApiFallbackFactory.class)
public interface Api {

}
```

3. 在单元测试中循环调用此接口的方法，通过抛出`java.net.ConnectException`异常模拟调不通的情况，未触发ApiFallback中的代码，在Sentinel的`${user_home}/logs/csp`日志目录中发现异常未计数：
<img width="618" alt="image" src="https://user-images.githubusercontent.com/864375/202384973-636bcd42-da4f-4849-b1fc-60aab9243702.png">

日志的第7个数值为异常数
<img width="794" alt="image" src="https://user-images.githubusercontent.com/864375/202385225-bc65aece-e726-4f2e-a0f1-c25817ec50c8.png">

4. 通过分析代码发现`SentinelRetrofitDegrade`类中未通过`Tracer`对异常进行统计：
```java
    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        Method method = Objects.requireNonNull(request.tag(Invocation.class)).method();
        SentinelDegrade sentinelDegrade = AnnotationExtendUtils.findMergedAnnotation(method, method.getDeclaringClass(),
                SentinelDegrade.class);
        if (!needDegrade(sentinelDegrade)) {
            return chain.proceed(request);
        }
        String resourceName = parseResourceName(method);
        Entry entry = null;
        try {
            entry = SphU.entry(resourceName, ResourceTypeConstants.COMMON_WEB, EntryType.OUT);
            return chain.proceed(request);
        } catch (BlockException e) {
            throw new RetrofitBlockException(e);
        } finally {
            if (entry != null) {
                entry.exit();
            }
        }
    }
```

<img width="794" alt="image" src="https://user-images.githubusercontent.com/864375/202386019-f9e2adb4-865a-4d26-9ff5-cc9e0f926faa.png">

5. 在Sentinel提供的sentinel-okhttp-adapter中的代码，包含了`Tracer`记录的代码：
https://github.com/alibaba/Sentinel/blob/master/sentinel-adapter/sentinel-okhttp-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/okhttp/SentinelOkHttpInterceptor.java
<img width="721" alt="image" src="https://user-images.githubusercontent.com/864375/202386567-9d7d587f-6987-41dd-a08a-0336df62e02e.png">

**Comment by shelltea** [comment]
在对`SentinelRetrofitDegrade`类进行了以下修改后，可以正常记录异常数，并触发熔断：

<img width="936" alt="image" src="https://user-images.githubusercontent.com/864375/202393538-2d8826d8-e83b-4638-918b-4fabb8c758c2.png">

<img width="717" alt="image" src="https://user-images.githubusercontent.com/864375/202393615-3ab5fb28-1b6d-4baa-b3f3-140f13bb958c.png">

5次异常，995次拦截。

**Comment by chentianming11** [comment]
感觉对于非BlockException，都需要trace
<img width="883" alt="image" src="https://user-images.githubusercontent.com/30620547/202435276-1266dee7-4ca5-4a3a-b231-b9e08612cb27.png">

2.3.10版本已修复

**Comment by shelltea** [comment]
@chentianming11 升级到了2.3.10，测试可以熔断。👍
