### ISSUE TITLE
 关于 @OkHttpClientBuilder

### ISSUE THREAD

**Issue by sky007z** [LianjiaTech/retrofit-spring-boot-starter#136]
@OkHttpClientBuilder  注解为啥给去掉了

**Comment by chentianming11** [comment]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/30620547/202603832-0752ea82-3b50-4a06-856b-732cc74a2d95.png">

新版本自定义OkHttpClient改成上面这种方式了。原来的`@OkHttpClientBuilder`对于自定义支持不够好，因此重构了这部分实现。
