### ISSUE TITLE
Spring Boot 3.0

### ISSUE THREAD

**Issue by efemoney** [LianjiaTech/retrofit-spring-boot-starter#137]
I don't think it works with the latest version of Spring Boot 3 & Framework 6.

**Comment by efemoney** [comment]
Framework upgrade guide: https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x

Boot upgrade guide: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide

**Comment by jeanpbond** [comment]
Just to add up a little bit, I migrate my project to Spring Boot 3 & Spring Framework 6 and I have the following error, I think it happened during the `@RetrofitScan` : 

```
11:14:37.959 [main] DEBUG o.s.b.d.LoggingFailureAnalysisReporter - Application failed to start due to an exception
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.lianjiatech.retrofit.spring.boot.config.RetrofitConfigBean' available
```

**Comment by chentianming11** [comment]
retrofit-spring-boot-starter 3.0.0  already supports it.

**Comment by efemoney** [comment]
I will test within this week and give feedback. Thanks!
