### ISSUE TITLE
如果返回类型是Single<T> 那么请求只能是异步的吗

### ISSUE THREAD

**Issue by hunao0221** [LianjiaTech/retrofit-spring-boot-starter#142]
之前一个项目用的是自己封装的`okhttp + rxjava`，api的返回类型统一为Observable<T>，现在想换成`retrofit-spring-boot-starter`，但看起来lib没有Observable的Converter，于是打算将返回类型统一为`Single<T>`,  发现它是一个异步调用。
不知道是我的使用方式不对，还是别的原因。

**Comment by chentianming11** [comment]
目前底层确实是使用异步方式的。

请问下，你这种场景用异步有什么问题吗？

**Comment by hunao0221** [comment]
> 目前底层确实是使用异步方式的。
> 
> 请问下，你这种场景用异步有什么问题吗？

okay, 只是想确认一下，那没什么了，谢谢哈。
