### ISSUE TITLE
@GET请求参数能否支持传入对象

### ISSUE THREAD

**Issue by XW512** [LianjiaTech/retrofit-spring-boot-starter#145]
我发现retrofit的@GET请求参数不支持传入对象，只能采用public String get(@QueryMap Map<String,Object> user)，只能先把传入的对象转换成map，能否像openfeign那样，通过@SpringQueryMap注入对象，例子如下：
public String get(@SpringQueryMap User user）

**Comment by chentianming11** [comment]
https://github.com/LianjiaTech/retrofit-spring-boot-starter/issues/145#issue-1565375469

**Comment by chentianming11** [comment]
没办法支持，Retrofit限制死了。自行实现一个将POJO转Map的工具类吧，这样也不算复杂
#150
