### ISSUE TITLE
retrofit client客户端无法注入 ： required a bean of type 'com.xxxx.cloud.rpc.xxxApi' that could not be found.

### ISSUE THREAD

**Issue by shen0834** [LianjiaTech/retrofit-spring-boot-starter#147]
Springboot version : 2.7.8
retrofit-spring-boot-starter version : 2.3.11

我试了2.3.8都无法注入，包括自己驱动`org.springframework.boot.autoconfigure.AutoConfiguration.imports` 到 `com.github.lianjiatech.retrofit.spring.boot.config.RetrofitAutoConfiguration` 还是无法初始化

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in com.xxx.cloud.adapter.web.someBean required a bean of type 'com.xxxx.cloud.rpc.xxxApi' that could not be found.

Action:

Consider defining a bean of type 'com.xxxx.cloud.rpc.xxxApi' in your configuration.

**Comment by shen0834** [comment]
大哥 ， 你的@RetrofitScan  这个注解应该在文档里面说明一下，对于分层架构来说， scan the same base package as Spring Boot does 并不好用，最后还得自己翻源码来解决

**Comment by feilongzait123** [comment]
大兄弟怎么解决的,我给这个注解单独指定到我的类都不生效
