### ISSUE TITLE
baseUrl从数据库获取怎么实现

### ISSUE THREAD

**Issue by gaoruiqiang2017** [LianjiaTech/retrofit-spring-boot-starter#148]
@RetrofitClient(baseUrl = "${test.baseUrl}"
baseUrl现在是在配置文件必填的，我的baseUrl可能是空值，如果不填就启动不了，
我想从数据库获取这样实现，获取不到baseUrl就不会调用api，
现在我必须在配置文件配置才能启动

**Comment by chentianming11** [comment]
无法支持，建议使用动态url控制请求调用

**Comment by ViicesCai** [comment]
> 无法支持，建议使用动态url控制请求调用

您好，关于动态请求；如果只有请求的IP与端口需要改变，请求的路径端点不变呢？使用@URL 的方式，其实不够完善，相当于把整个请求路径作动态替换了？能保留原始的请求端点只改变请求的IP吗？

**Comment by chentianming11** [comment]
不好意思，你之前说的使用ServiceInstanceChooser也是可以实现的，并且确实更符合你的要求。

**Comment by ViicesCai** [comment]
ServiceInstanceChooser 可能也不太符合我的需求，我的 ip 可能是接口传过来，我目前的做法是 使用接口定义HTTP代理请求，然后通过包装 Retrofit 的调用，动态的传入URL路径与请求的代理接口，然后在这个封装的对象类对请求的一些响应作统一的处理。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月16日 19:24
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [LianjiaTech/retrofit-spring-boot-starter] baseUrl从数据库获取怎么实现 (Issue #148)


不好意思，你之前说的使用ServiceInstanceChooser也是可以实现的，并且确实更符合你的要求。

―
