### ISSUE TITLE
数据转码有bug

### ISSUE THREAD

**Issue by zhuanghuijian** [LianjiaTech/retrofit-spring-boot-starter#151]
数据转码请求如果是body参数，对象转json有bug
    @JsonAlias("userid")
    private String userId;
应该转的json 格式是userid的。但是还是用到userId了。没有用到alias指定的值。

**Comment by chentianming11** [comment]
对象转json使用@JsonProperty，而不是@JsonAlias。@JsonAlias只影响反序列化，不影响序列化。
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/30620547/231441957-24da8cb0-0f22-4a65-8511-613dec78d866.png">
