### ISSUE TITLE
自定义OkHttpClient中的属性，需要每个@RetrofitClient.sourceOkHttpClient指定当前接口要使用的OkHttpClient

### ISSUE THREAD

**Issue by XW512** [LianjiaTech/retrofit-spring-boot-starter#154]
你好，如果我需要自定义OkHttpClient的属性，主要是设置连接池或者超时的时间配置，需要在每个@RetrofitClient.sourceOkHttpClient中指定自定义的OkHttpClient吗？如果我要使它全局生效，可以怎么配置

**Comment by chentianming11** [comment]
1、超时时间有全局配置
<img width="462" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/30620547/c27d7166-efdb-4181-b6c5-4df5e99fcd5c">
2、 如果是其他的配置，可以自定义一个RetrofitClient的注解，覆盖sourceOkHttpClient，后续都使用这个自定义注解即可。
<img width="929" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/30620547/77d3ff69-5afb-47a1-87a8-75c7d41f7fc6">

**Comment by XW512** [comment]
> 1、超时时间有全局配置 <img alt="image" width="462" src="https://user-images.githubusercontent.com/30620547/237994849-c27d7166-efdb-4181-b6c5-4df5e99fcd5c.png"> 2、 如果是其他的配置，可以自定义一个RetrofitClient的注解，覆盖sourceOkHttpClient，后续都使用这个自定义注解即可。 <img alt="image" width="929" src="https://user-images.githubusercontent.com/30620547/237995263-77d3ff69-5afb-47a1-87a8-75c7d41f7fc6.png">

好的，感谢感谢
