### ISSUE TITLE
retry是否能够增加日志

### ISSUE THREAD

**Issue by HsinDumas** [LianjiaTech/retrofit-spring-boot-starter#158]
提一个需求，能不能把retry中出错的请求日志也打印一下
现在只有最后一次请求的日志

**Comment by chentianming11** [comment]
<img width="798" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/30620547/33683198-6060-4816-8063-6b94db6b67ca">
可以自行扩展支持的

**Comment by chentianming11** [comment]
现在已经优化成，retry和熔断都会打印日志
