### ISSUE TITLE
ServiceInstanceChooser 实现类无法注入 LoadBalancerClient

### ISSUE THREAD

**Issue by bjsnake** [LianjiaTech/retrofit-spring-boot-starter#160]
环境：jdk17
retrofit-spring-boot-starter  3.0.2

<img width="894" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/107290000/3ce6389b-a1f6-4079-8015-aec5cfdca18d">

<img width="836" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/107290000/dfbb7b3c-4c7b-4b7d-b82a-ead32c22d263">
<img width="1399" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/107290000/6c1a8afb-7155-4b66-8400-5d5cda41e1ca">

**Comment by yxjinchao** [comment]
目前自己写了一个简单的本地轮训负载算法

如下：

<img width="897" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/107290000/5250ef3f-69d2-4356-90e9-d63ef8a44f97">

<img width="915" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/107290000/891ad355-5e58-4f0a-b0fd-1084d983b811">

<img width="1393" alt="image" src="https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/107290000/e34ca3c6-7d47-489f-99e3-3c1731a05d71">

希望官方能实现一个整合nacos的实现

**Comment by chentianming11** [comment]
麻烦还是自己实现吧，实在没精力搞naco实现了
