### ISSUE TITLE
拦截器兼容性不行

### ISSUE THREAD

**Issue by look2J** [LianjiaTech/retrofit-spring-boot-starter#164]
<dependency>
    <groupId>com.github.lianjiatech</groupId>
    <artifactId>retrofit-spring-boot-starter</artifactId>
    <version>3.0.2</version>
</dependency>
该版本的拦截器
Method method = ((Invocation)Objects.requireNonNull((Invocation)request.tag(Invocation.class))).method();
要求必须存在Invocation、Method ，兼容性不够好，旧项目有些事直接使用httpClient的，引入retrofit-spring-boot-starter之后，自动注入此拦截器并每次都会拦截，然后由于没有Invocation、Method所以报错了，我理解所有的拦截器都不要强制性要求存在Invocation、Method 这些，没有，那就当做普通的http请求来调用

**Comment by chentianming11** [comment]
目前相关拦截器逻辑是强依赖Invocation、Method的，不过确实可以优化成没有的时候不抛错。

**Comment by chentianming11** [comment]
新版本已支持
