### ISSUE TITLE
2.2.14 版本, FallbackFactory 不生效.

### ISSUE THREAD

**Issue by java001** [LianjiaTech/retrofit-spring-boot-starter#167]
不生效的原因是因为: RetrofitInvocationHandler 里面抛的异常不是: RetrofitBlockException.
![image](https://github.com/LianjiaTech/retrofit-spring-boot-starter/assets/21332033/47ad01b5-7842-4751-9510-ff78b10c09fa)

升级版本后,  RetrofitClient 的接口无法扫描到, 导致注入不进来.

**Comment by chentianming11** [comment]
不是`RetrofitBlockException `，说明不是熔断导致的异常，因此不能走熔断逻辑。

**Comment by chentianming11** [comment]
升级到哪个版本注入不了？

**Comment by java001** [comment]
2.3.14注入不了, 我用spring的扫描和RetrofitScan都试过了, 还是提示报错, 不知道是不是扫描多次会失效, 或者是顺序的问题.

**Comment by java001** [comment]
那不是熔断的异常, 要怎么统一处理? 我想统计接口的异常数量.

**Comment by chentianming11** [comment]
可以自行实现一个拦截器统计

**Comment by java001** [comment]
@Intercept 新加一个这个? 然后try一下吗?

**Comment by java001** [comment]
继承 BaseGlobalInterceptor , try了存库里面了.
