### ISSUE TITLE
升级 retrofit  2.11.0

### ISSUE THREAD

**Issue by melin** [LianjiaTech/retrofit-spring-boot-starter#171]
<dependency>
    <groupId>com.squareup.retrofit2</groupId>
    <artifactId>retrofit</artifactId>
    <version>2.11.0</version>
</dependency>
https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit/2.11.0

**Comment by chentianming11** [comment]
Versions 2.4.0 and 3.1.0 are already supported
