### ISSUE TITLE
ServiceChooseInterceptor中必须指定端口问题

### ISSUE THREAD

**Issue by vm0100** [LianjiaTech/retrofit-spring-boot-starter#179]
ServiceChooseInterceptor中会构造一个HttpUrl，构造HttpUrl时获取了URL的port属性， 如果URL未指定port会导致报错。  

可否使用getDefaultPort()兼容一下，因为如果使用域名请求时基本上是不会写入port的，所以在字符串转URI时port获取一定是-1

<img width="1162" alt="image" src="https://github.com/user-attachments/assets/e26f4180-d03e-4bd5-897a-8dfcdc7a5bcc">
<img width="616" alt="image" src="https://github.com/user-attachments/assets/fe526c9b-7e29-4df7-8b97-ad0302a63c46">

**Comment by chentianming11** [comment]
该问题在3.1.3 /  2.4.3 已修复
