### ISSUE TITLE
处理500响应

### ISSUE THREAD

**Issue by lly835** [LianjiaTech/retrofit-spring-boot-starter#19]
比如请求某网站返回500，代表登录失效。我发现用
`Response<String>` 
是拿不到响应的，文档上说[如果http状态码不是2xx，直接抛错！]   控制台也没看到抛错

**Comment by chentianming11** [comment]
如果是500，现在默认在ErrorDecoder层就会抛出异常，因此Response<String>确实是拿不到响应的。控制台没异常堆栈，这个可能麻烦贴一下代码。下图是单元测试返回500的异常堆栈：
![image](https://user-images.githubusercontent.com/30620547/93433089-f2f5e300-f8f8-11ea-923b-446e3f4c66c1.png)

**Comment by lly835** [comment]
我试了下，在自定义的ErrorDecoder里抛出自定义异常LoginException，最后也会变成RetrofitException异常。。。
其实我需要在调用client的时候捕获LoginException


 原始邮件 
发件人: 六点半起床<notifications@github.com>
收件人: LianjiaTech/retrofit-spring-boot-starter<retrofit-spring-boot-starter@noreply.github.com>
抄送: lly835<lly835@163.com>; Author<author@noreply.github.com>
发送时间: 2020年9月17日(周四) 15:18
主题: Re: [LianjiaTech/retrofit-spring-boot-starter] 处理500响应 (#19)


如果是500，现在默认在ErrorDecoder层就会抛出异常，因此Response确实是拿不到响应的。控制台没异常堆栈，这个可能麻烦贴一下代码。下图是单元测试返回500的异常堆栈：

**Comment by chentianming11** [comment]
异常在Adapter层又被包了一层，确实不太合理，我马上发一个小版本修复，感谢建议~

**Comment by chentianming11** [comment]
2.1.6版本已修复这个问题，可以尝试一下~ 新版本大概下午5点左右推到中央仓库

**Comment by lly835** [comment]
好的

**Comment by chentianming11** [comment]
2.1.6版本是否已经解决了这个问题？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LianjiaTech/retrofit-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午5:01
收件人:&nbsp;"LianjiaTech/retrofit-spring-boot-starter"<retrofit-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"陈添明"<chentianming11@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LianjiaTech/retrofit-spring-boot-starter] 处理500响应 (#19)





 
好的

**Comment by lly835** [comment]
还没有试，因为我改了下源码，为了支持  https://github.com/LianjiaTech/retrofit-spring-boot-starter/issues/18

**Comment by chentianming11** [comment]
接口可配置converter已经开发完成，今天会发一个新版本支持。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LianjiaTech/retrofit-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 下午4:00
收件人:&nbsp;"LianjiaTech/retrofit-spring-boot-starter"<retrofit-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"陈添明"<chentianming11@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LianjiaTech/retrofit-spring-boot-starter] 处理500响应 (#19)





 
还没有试，因为我改了下源码，为了支持  #18
