### ISSUE TITLE
考虑使用springboot JacksonAutoConfiguration提供的ObjectMapper替代自定义的

### ISSUE THREAD

**Issue by JiaRG** [LianjiaTech/retrofit-spring-boot-starter#2]
https://github.com/LianjiaTech/retrofit-spring-boot-starter/blob/b6d2a1cef0901df407faa2fd146667e3b498eacc/src/main/java/com/github/lianjiatech/retrofit/spring/boot/config/RetrofitAutoConfiguration.java#L87-L89

**Comment by chentianming11** [comment]
好建议，后续优化一下~

**Comment by chentianming11** [comment]
2.0.3版本 支持通过spring.jackson.*配置retrofit jackson 序列化规则
