### ISSUE TITLE
Failed to run with unit test

### ISSUE THREAD

**Issue by minhnguyenvan95** [LianjiaTech/retrofit-spring-boot-starter#22]
Received this error when trying to build source with test

`
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException
            Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException

`

**Comment by chentianming11** [comment]
Can you provide a complete exception stack and the version of spring-boot used?
retrofit-spring-boot-starter depends on the spring-boot project, and the unit test can refer to the unit test of the source code.

**Comment by minhnguyenvan95** [comment]
Just resolve It , I have to mock my retrofit component
