### ISSUE TITLE
No RetrofitClient was found in '[com.github.lianjiatech.retrofit.spring.boot.test]' package. Please check your configuration.

### ISSUE THREAD

**Issue by gitQiao** [LianjiaTech/retrofit-spring-boot-starter#26]
No RetrofitClient was found in '[com.github.lianjiatech.retrofit.spring.boot.test]' package. Please check your configuration.

**Comment by chentianming11** [comment]
@RetrofitScan("com.github.lianjiatech.retrofit.spring.boot.test")
