### ISSUE TITLE
@Intercept中使用service调用相同的@RetrofitClient会变为空

### ISSUE THREAD

**Issue by zhuqi7y** [LianjiaTech/retrofit-spring-boot-starter#28]
使用的是retrofit-spring-boot-starter版本2.1.7

测试代码==>
接口TestApi ：
@RetrofitClient(baseUrl = "http:localhost:8081/", logStrategy = LogStrategy.BODY)
@Intercept(include = "/**", handler = TestIntercept.class)
public interface TestApi {
    @GET("test")
    JSONObject test();
}
拦截器：
@Component
public class TestIntercept extends BasePathMatchInterceptor {
    @Autowired
    private TestService testService;
    @Override
    protected Response doIntercept(Chain chain) throws IOException {
        System.out.println("testService is null? " + Objects.isNull(testService));
        return chain.proceed(chain.request());
    }
}
关键的service：
@Service
public class TestService {
    //下面两行注释掉，TestIntercept的testService就不会为空
    @Autowired
    private TestApi testApi;
}
调用controller测试：
@RestController("testController2")
public class TestController {
    @Autowired
    private TestApi testApi;
    @RequestMapping("/test")
    public JSONObject test() {
        return testApi.test();
    }
}
控制台输出结果：testService is null? true
将TestService里的@Autowired private TestApi testApi;注释掉后
输出结果为testService is null? false

为什么会发现这个问题呢，
因为有一个使用场景，调用一些接口需要一个令牌参数校验。
所以用路径拦截器添加一个令牌参数，但是这个令牌是有有效期的，存在缓存里，
获取令牌的接口也在相同的@RetrofitClient下面
在业务层判断缓存里获取这个令牌，如果缓存里过期需要重新调接口获取令牌。
如果把获取令牌的接口，和其他在需要在参数中添加令牌的接口分别建立两个@RetrofitClient就不会有上面的问题
这可能是为了防止循环调用的问题把

**Comment by chentianming11** [comment]
嗯，确实可能和spring的循环依赖机制有关，后续我会跟进研究一下~

**Comment by JakeWoki** [comment]
没相同的也为空
```Java
@Retry
@RetrofitClient(
        baseUrl = "https://api.weixin.qq.com/",
        fallback = HttpApiFallback.class,
        fallbackFactory = HttpDegradeFallbackFactory.class,
        logStrategy = LogStrategy.BODY
)
/*默认策略情况下，每5s平均响应时间不得超过500ms，否则启用熔断降级*/
/*默认策略情况下，每5s平均响应时间不得超过500ms，否则启用熔断降级*/
@Degrade(count = 500.0)
public interface HttpApi {

    /**
     * 构建出的这个方法一定一定要加  @OkHttpClientBuilder 这个注解
     *
     * @return
     */
    @OkHttpClientBuilder
    static OkHttpClient.Builder okhttpClientBuilder() {
        return new OkHttpClient.Builder()
                .connectTimeout(1, TimeUnit.SECONDS)
                .readTimeout(1, TimeUnit.SECONDS)
                .writeTimeout(1, TimeUnit.SECONDS);

    }

    @GET("sns/jscode2session")
    Response<String> jsCodeToSession(@Query("js_code") String jsCode, @Query("appid") String appId, @Query("secret") String secret, @Query("grant_type") String grantType);
}
```
```Java
/**
 * 微信登陆鉴权 Provider，要求实现 AuthenticationProvider 接口
 */
public class WXAuthenticationProvider implements AuthenticationProvider {
@Autowired
    private HttpApi httpApi;

    @Override
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        String result = httpApi.jsCodeToSession(code, wxProperties.getAppId(), wxProperties.getSecret(), "authorization_code").body();
    }
}
```
这样httpApi也是空的
