### ISSUE TITLE
怎么单独禁止某个接口的body转换

### ISSUE THREAD

**Issue by JackyLeeCS** [LianjiaTech/retrofit-spring-boot-starter#34]
某个第三方接口的Content-Type为text/plain，但是body里面传字符串会被加上双引号，怎么单独对这个接口禁止body转换，其它的接口还是需要正常转换，这个接口的返回值也需要正常转换。

**Comment by chentianming11** [comment]
前面的是指request请求转换吗？

**Comment by alewu** [comment]
同问
