### ISSUE TITLE
构造器注入的时候 能够像mybatis mapper那样不要报 no beans found 吗？

### ISSUE THREAD

**Issue by qinkangdeid** [LianjiaTech/retrofit-spring-boot-starter#35]
如题 构造器注入的时候 能够像mybatis mapper那样不要报 no beans found 吗？
![image](https://user-images.githubusercontent.com/17582522/98228441-8f507380-1f93-11eb-99ff-d78842179454.png)
虽然bean是已经有了 就是报这个警告 不是很爽 hahahah😂

**Comment by chentianming11** [comment]
👍，后续研究一下

**Comment by chentianming11** [comment]
![image](https://user-images.githubusercontent.com/30620547/99361757-8e9dd280-28ed-11eb-9733-333ff9b1a35f.png)
兄弟，我刚刚看了下，Mybatis的Mapper一样也有这个警告😂

**Comment by stupdit1t** [comment]
这个就是编译器检测等级的问题，把等级拉到中等

**Comment by freshgeek** [comment]
可以使用@Resource 注解 避免 ，
