### ISSUE TITLE
微服务之间调用

### ISSUE THREAD

**Issue by demidroid** [LianjiaTech/retrofit-spring-boot-starter#36]
大神，能不能把微服务调用的地方写个例子，文档描述的看不懂，谢谢

**Comment by chentianming11** [comment]
![image](https://user-images.githubusercontent.com/30620547/98618760-ced4e200-233c-11eb-9a9e-49034dff4869.png)
刚刚更新了一下文档。第一步是配置Bean，第二步使用@Retrofit的serviceId和path进行使用。
