### ISSUE TITLE
启动报这个错，@RetrofitScan这个注解应该加在哪里

### ISSUE THREAD

**Issue by qinshaokang** [LianjiaTech/retrofit-spring-boot-starter#42]
FactoryBean threw exception on object creation; nested exception is java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder;

**Comment by chentianming11** [comment]
> FactoryBean threw exception on object creation; nested exception is java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder;

正常情况下不需要配置@RetrofitScan注解，这个报错是okhttp3版本问题，请使用3.14.9及以上版本。
ps：@RetrofitScan配置在启动类上即可

**Comment by chamhaw** [comment]
建议okhttp版本跟着retrofit版本走吧，retrofit 2.9.0 依赖了3.8.1， 你这里使用了3.14.9的特性，大概率冲突

**Comment by chentianming11** [comment]
retrofit 2.9.0 依赖的是3.14.9


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LianjiaTech/retrofit-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 上午10:24
收件人:&nbsp;"LianjiaTech/retrofit-spring-boot-starter"<retrofit-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"陈添明"<chentianming11@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LianjiaTech/retrofit-spring-boot-starter] 启动报这个错，@RetrofitScan这个注解应该加在哪里 (#42)





 
建议okhttp版本跟着retrofit版本走吧，retrofit 2.9.0 依赖了3.8.1， 你这里使用了3.14.9的特性，大概率冲突

**Comment by 15695521334** [comment]
我的开始也报这个错，然后按上面更新了版本，
![image](https://user-images.githubusercontent.com/72637180/103724273-e532ad80-500e-11eb-87af-bbdf4b861540.png),截图如上。结果报另外一个错，如下：
	... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: okhttp3.Interceptor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 common frames omitted
