### ISSUE TITLE
关于retrofit-spring-boot-starter和RestTemplate的比较

### ISSUE THREAD

**Issue by guohongtao0214** [LianjiaTech/retrofit-spring-boot-starter#5]
使用微服务，Spring Cloud，服务与服务之间都是通过RestTemplate来调用，项目中也通过设置ConnectionFactory，改成了OkHttp3ClientHttpRequestFactory。但是还是用到了RestTemplate，因为默认的@LoadBalanced只对RestTemplate生效，retrofit不支持Spring Cloud的负载均衡吧。只可以在一些调用外部接口的服务上用。

**Comment by chentianming11** [comment]
retrofit是基于okhttp的声明式调用封装，个人感觉Spring Cloud还是用openFeign最简单，因为整合了很多功能。retrofit更加轻量，单纯的spring-boot项目可以考虑使用。
