### ISSUE TITLE
有没有办法忽略ssl证书校验

### ISSUE THREAD

**Issue by wmlz** [LianjiaTech/retrofit-spring-boot-starter#50]
在测试环境ssl证书错误比较常见,有没有办法忽略

否则会报这个错
com.github.lianjiatech.retrofit.spring.boot.exception.RetrofitIOException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target,

**Comment by yangxing19930210** [comment]
请问解决了吗，我也遇到同样的问题

**Comment by yangxing19930210** [comment]
@OkHttpClientBuilder
    static OkHttpClient.Builder okhttpClientBuilder() {
        return new OkHttpClient.Builder().connectTimeout(1, TimeUnit.SECONDS).readTimeout(1, TimeUnit.SECONDS)
            .writeTimeout(1, TimeUnit.SECONDS).sslSocketFactory(SSLSocketConfig.getSSLSocketFactory())
            .hostnameVerifier(SSLSocketConfig.getHostnameVerifier());

    }

**Comment by yangxing19930210** [comment]
public class SSLSocketConfig {
    // 获取这个SSLSocketFactory
    public static SSLSocketFactory getSSLSocketFactory() {
        try {
            SSLContext sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, getTrustManager(), new SecureRandom());
            return sslContext.getSocketFactory();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // 获取TrustManager
    private static TrustManager[] getTrustManager() {
        TrustManager[] trustAllCerts = new TrustManager[] {new X509TrustManager() {
            @Override
            public void checkClientTrusted(X509Certificate[] chain, String authType) {}

            @Override
            public void checkServerTrusted(X509Certificate[] chain, String authType) {}

            @Override
            public X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[] {};
            }
        }};
        return trustAllCerts;
    }

    // 获取HostnameVerifier
    public static HostnameVerifier getHostnameVerifier() {
        HostnameVerifier hostnameVerifier = new HostnameVerifier() {
            @Override
            public boolean verify(String s, SSLSession sslSession) {
                return true;
            }
        };
        return hostnameVerifier;
    }
}

**Comment by Lyn265** [comment]
请问，我项目里依赖了一个第三方SDK，这个SDK也是spirngboot构建，并且底层也依赖Okhttp3，请问我能做一些配置来覆盖SDK里的默认配置忽略证书校验问题吗，
