### ISSUE TITLE
如何处理json返回不同的类型

### ISSUE THREAD

**Issue by lly835** [LianjiaTech/retrofit-spring-boot-starter#52]
正常是返回数据，异常会返回空数组

## 正常
{"code":10888,"message":"未登录","data":{"uid": 1}}

## 异常
{"code":88,"message":"未登录","data":[]}

目前我将data定义成对象。遇到异常的情况会报错
com.github.lianjiatech.retrofit.spring.boot.exception.RetrofitIOException: Cannot deserialize instance of `com.demo.xxxx` out of START_ARRAY token

**Comment by chentianming11** [comment]
可以尝试data使用Object接收，然后在使用的时候根据code值，手动取data数据数据进行处理😂。
