### ISSUE TITLE
返回适配器转换问题

### ISSUE THREAD

**Issue by azoveh** [LianjiaTech/retrofit-spring-boot-starter#53]
返回数据为一个对象，里面有一个List，和总数据条数，但LIST 转换出来为空， 总条数正常，用OBJECT接收正常

返回数据
{
  "tCarDTOS": [
    {
      "vehicleNo": "鲁B1WG70",
      "plateColor": "蓝色",
      "vehicleType": "小型轿车",
      "ownerName": "个人",
      "vehicleColor": "",
      "certifyDateA": "19700101",
      "transArea": "青岛",
      "certifyDateB": "20200102",
      "fareType": 1,
      "fuelType": "汽油",
      "commercialType": 1,
      "updateTime": "20200422",
      "cityId": 60
    },
    {
      "vehicleNo": "鲁2NJ0",
      "plateColor": "蓝色",
      "vehicleType": "小型轿车",
      "brand": "大众",
      "model": "朗逸",
      "ownerName": "陈好",
      "vehicleColor": "",
      "certifyDateA": "20170814",
      "transArea": "青岛",
      "certifyDateB": "20200104",
      "fareType": 1,
      "fuelType": "汽油",
      "commercialType": 1,
      "updateTime": "20200422",
      "cityId": 60
    }
  ],
  "totalCount": 22301
}

接收对象
public class DriverDto {
    List<MtVehicle> tDriverDTOS;
    Integer totalCount;
}

实际转换结果
![image](https://user-images.githubusercontent.com/32286100/108591348-49cd8000-73a3-11eb-9ba3-1932748ed21d.png)

**Comment by chentianming11** [comment]
这个是JSON转换问题，第一个字母小写，第二个大写会有问题，我之前也碰到这种坑了。两种解决方案：
1、更改字段名
2、使用Map接收返回值
