### ISSUE TITLE
使用含有@Body的@Get方法报错:Non-body HTTP method cannot contain @Body.

### ISSUE THREAD

**Issue by leesonwei** [LianjiaTech/retrofit-spring-boot-starter#55]
Hi, 我的问题如下:
  我使用retrofit调用Kafka Rest接口, 接口要求使用Get方法,并且须带有一个Json格式的body,我的定义如下
`@Headers({"Content-Type:application/vnd.kafka.json.v2+json"})
 @GET("consumers/{group_name}/instances/{instance_name}/offsets")
 Call<JsonNode> getOffsets(@Path("group_name") String groupName, @Path("instance_name") String instanceName,
                              @Body RequestBody body);`

执行时报错: Non-body HTTP method cannot contain @Body.
可否协助解决?

**Comment by chentianming11** [comment]
按照HTTP规范，get请求方式就是不支持请求体的😂  
所以，不太理解“Get方法,并且须带有一个Json格式的body”具体指什么。

**Comment by leesonwei** [comment]
> 按照HTTP规范，get请求方式就是不支持请求体的😂
> 所以，不太理解“Get方法,并且须带有一个Json格式的body”具体指什么。

感谢您的回复:
我这里有个API,它的文档如下:
`GET /consumers/testgroup/instances/my_consumer/offsets HTTP/1.1
Host: proxy-instance.kafkaproxy.example.com
Content-Type: application/vnd.kafka.v2+json, application/vnd.kafka+json, application/json
#parameters
{
  "partitions": [
    {
      "topic": "test",
      "partition": 0
    },
    {
      "topic": "test",
      "partition": 1
    }

  ]
}`
请教应该如何用retrofit创建该请求?谢谢!

**Comment by chentianming11** [comment]
今天查了下，get确实可以传body，但是一般不推荐这么使用。我研究一下retrofit怎么传😂，之前没碰到过

**Comment by chentianming11** [comment]
@HTTP(method = "GET", path = "/user/get", hasBody = true)
试试这种方式看看~

**Comment by leesonwei** [comment]
> `@HTTP(method = "GET", path = "/user/get", hasBody = true)`
> 试试这种方式看看~

感谢, 这个方式报错信息意思一样. 还是通不过

**Comment by chentianming11** [comment]
> > `@HTTP(method = "GET", path = "/user/get", hasBody = true)`
> > 试试这种方式看看~
> 
> 感谢, 这个方式报错信息意思一样. 还是通不过

okhttp3自身不支持`GET`请求带请求体。源码如下：
![image](https://user-images.githubusercontent.com/30620547/108949806-0a9f7780-76a0-11eb-9eb4-326d5d546e98.png)
![image](https://user-images.githubusercontent.com/30620547/108949831-1ab75700-76a0-11eb-955c-95d324084580.png)

作者给出了具体原因，可以参考这个issue：https://github.com/square/okhttp/issues/3154

but，如果实在需要这么干，我想到一种方式，可以使用`@HTTP(method = "get", path = "/user/get", hasBody = true)`。使用小写`get`绕过上述限制。可以尝试一下！

**Comment by leesonwei** [comment]
谢谢. 不过小写的get对我不起作用, kafka端不允许get请求,只允许GET请求. 不过我看了很多http客户端(apache httpclient, spring webclient等), 基本上都不支持get带body. 看来只能用最原始的方法了. 再次谢谢您的帮助!
