### ISSUE TITLE
日志拦截器能用注解使用吗

### ISSUE THREAD

**Issue by wangran99** [LianjiaTech/retrofit-spring-boot-starter#6]
如题

**Comment by chentianming11** [comment]
目前日志是统一内置的，可以通过@RetrofitClient定义每个接口下日志的打印级别和打印策略，还支持配置自定义的日志拦截器。
你这个需求，是不是希望可以针对每个接口自定义是否开启日志打印功能？

**Comment by chentianming11** [comment]
如果是上述情况，@RetrofitClient可以新增支持一个boolean类型，支持是否开启日志打印功能。至于日志怎么打印，可以指定日志打印拦截器。

**Comment by chentianming11** [comment]
2.0.4版本 @RetrofitClient新增enableLog属性，支持接口级别是否启用日志打印配置。
