### ISSUE TITLE
使用retrofit訪問地址 出現重試錯誤，但使用cul或者瀏覽器訪問正常，在同一程序中使用hutool的HttpUtil也是正常響應

### ISSUE THREAD

**Issue by Zbuter** [LianjiaTech/retrofit-spring-boot-starter#62]
訪問某些https網址會出現錯誤：
Retry Failed: Total 2 attempts made at interval 100ms, request=Request{method=GET, url=。。。
使用cul或者瀏覽器訪問正常，在同一程序中使用Hutool的HttpUtil.get()訪問同一網址都能夠得到正確相應。

**Comment by Zbuter** [comment]
已找到解决办法。

**Comment by jitwxs** [comment]
请问如何解决?
