### ISSUE TITLE
请问如何设置请求的超时时间呢

### ISSUE THREAD

**Issue by tomdegithub** [LianjiaTech/retrofit-spring-boot-starter#63]
retrofit-spring-boot-starter 2.0.2，有一个同步接口超时了，是数据太多造成的超时，想要增加超时时间

**Comment by Zbuter** [comment]
作者在readme中都写了。
在 标注@RetrofitClient注解的那个接口 中添加如下：
@OkHttpClientBuilder
    static OkHttpClient.Builder okhttpClientBuilder() {
        return new OkHttpClient.Builder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS);
    }

**Comment by chentianming11** [comment]
> 作者在readme中都写了。
> 在 标注@RetrofitClient注解的那个接口 中添加如下：
> @OkHttpClientBuilder
> static OkHttpClient.Builder okhttpClientBuilder() {
> return new OkHttpClient.Builder()
> .connectTimeout(60, TimeUnit.SECONDS)
> .readTimeout(60, TimeUnit.SECONDS)
> .writeTimeout(60, TimeUnit.SECONDS);
> }

如果只是配置超时时间，设置@RetrofitClient的相关属性就可以了

**Comment by tomdegithub** [comment]
> 作者在自述中都写了。
> 在标注@RetrofitClient注解的那个接口中添加如下：
> @OkHttpClientBuilder
> 静态OkHttpClient.Builder okhttpClientBuilder（）{
> 返回新OkHttpClient.Builder（）
> .connectTimeout（60 TimeUnit.SECONDS）
> .readTimeout（60 ，TimeUnit.SECONDS）
> .writeTimeout（60，TimeUnit.SECONDS）;
> }

你可能没看清楚我用的版本，我用的版本没有这个注解

**Comment by tomdegithub** [comment]
> > 作者在自述中都写了。
> > 在标注@RetrofitClient注解的那个接口中添加如下：
> > @OkHttpClientBuilder
> > 静态OkHttpClient.Builder okhttpClientBuilder（）{
> > 返回新OkHttpClient.Builder（）
> > .connectTimeout（60 TimeUnit.SECONDS）
> > .readTimeout（60 ，TimeUnit.SECONDS）
> > .writeTimeout（60，TimeUnit.SECONDS）; 
> > }
> 
> 如果只是配置超时时间，设置@RetrofitClient的相关属​​性就可以了

请问在2.0.2这个版本该怎么设置超时时间呢，我尝试了给okhttp设置超时时间但是并没有用

**Comment by tomdegithub** [comment]
给我提供的接口太垃圾了，要18秒才能请求完数据，我说用队列同步数据就是了，这些人死活不用，非要直接请求接口同步数据

**Comment by tomdegithub** [comment]
问题补充，我这里目前springboot使用2.1.3.RELEASE，retrofit-spring-boot-starter 2.0.2，项目组要求不能换boot版本，我尝试了其他retrofit-spring-boot-starter版本但是启动项目会报错，而目前使用的retrofit-spring-boot-starter 2.0.2没有@OkHttpClientBuilder这个注解

**Comment by chentianming11** [comment]
> 问题补充，我这里目前springboot使用2.1.3.RELEASE，retrofit-spring-boot-starter 2.0.2，项目组要求不能换boot版本，我尝试了其他retrofit-spring-boot-starter版本但是启动项目会报错，而目前使用的retrofit-spring-boot-starter 2.0.2没有@OkHttpClientBuilder这个注解

2.0.2  `@RetrofitClient `注解可以设置超时时间。

**Comment by tomdegithub** [comment]
> > 问题补充，我这里目前springboot使用2.1.3版本，retrofit-spring-boot-starter 2.0.2，项目组要求不能换启动版本，我尝试了其他retrofit-spring-boot-starter版本但是启动项目会报错，而目前使用的retrofit-spring-boot-starter 2.0.2没有@OkHttpClientBuilder这个注解
> 
> 2.0.2 `@RetrofitClient `注解可以设置超时时间。

谢谢，非常感谢，看了一下有个readTimeoutMs属性，设置后就好使了！
