### ISSUE TITLE
@RetrofitClient注解配置baseUrl只支持不带path的host？

### ISSUE THREAD

**Issue by ImmortalFan** [LianjiaTech/retrofit-spring-boot-starter#64]
@RetrofitClient注解配置baseUrl只支持不带path的host吗？比如https://host:port/这样没问题，如果是https://host:pott/xxx，xxx会丢失

**Comment by Zbuter** [comment]
替作者回复一下 ： 
> 方法请求路径慎用/开头。对于Retrofit而言，如果baseUrl=http://localhost:8080/api/test/，方法请求路径如果是person，则该方法完整的请求路径是：http://localhost:8080/api/test/person。而方法请求路径如果是/person，则该方法完整的请求路径是：http://localhost:8080/person。

**Comment by verup** [comment]
如果用的是serviceId，则不管请求路径是否以"/"开头，都会丢失。且默认的port为-1会抛出异常。
