### ISSUE TITLE
在相同的项目中如果引用的包中已经使用了@RetrofitScan后，当前Spring-boot项目必须配置@RetrofitScan，不然就扫描不到对应的包

### ISSUE THREAD

**Issue by wushengju** [LianjiaTech/retrofit-spring-boot-starter#71]
解决办法:

RetrofitAutoConfiguration该类中加入@Import({AutoConfiguredRetrofitScannerRegistrar.class})

**Comment by chentianming11** [comment]
@RetrofitScan和自动装配是2选1的关系。这种场景，建议还是配置@RetrofitScan
