### ISSUE TITLE
有这样一个场景，先用Get请求调用登录接口，返回token,然后将token设置到下一个业务接口的header上，再通过POST请求调用

### ISSUE THREAD

**Issue by zhlid** [LianjiaTech/retrofit-spring-boot-starter#76]
有这样一个场景，先用Get请求调用登录接口，返回token,然后将token设置到下一个业务接口的header上，再通过POST请求调用，请问如何通过拦截器动态设置POST请求的header为get请求返回的token?

**Comment by chentianming11** [comment]
拦截器支持动态修改header的，网上有很多例子
