### ISSUE TITLE
配置日志，不生效， retrofit.version 2.2.17

### ISSUE THREAD

**Issue by feng-dan** [LianjiaTech/retrofit-spring-boot-starter#89]
## 你好，配置日志信息，不生效。
![image](https://user-images.githubusercontent.com/29519215/146748837-53ecfaef-5357-4bb0-87e4-68485fedc5a1.png)

![image](https://user-images.githubusercontent.com/29519215/146749052-b9598159-bb47-42ab-9e83-13bd3d195bd8.png)

![image](https://user-images.githubusercontent.com/29519215/146749223-a91ec0b7-50f1-4b22-914f-633af07f0600.png)

**Comment by chentianming11** [comment]
实际打印的日志信息是什么？

**Comment by feng-dan** [comment]
任何 retrofit 相关请求信息 日志都没有打印

**Comment by feng-dan** [comment]
日志框架配置 logback

**Comment by chentianming11** [comment]
![image](https://user-images.githubusercontent.com/30620547/147206791-eb0e5f05-9a29-4776-ae80-77de0005e65c.png)
启动的时候debug一下，日志打印拦截器是否正常添加进去了？

如果添加进去了，再看看日志打印拦截器的拦截方法是否正常工作。
![image](https://user-images.githubusercontent.com/30620547/147206942-9e5aa408-9eaa-427b-92b9-b0fdc3c782d9.png)

**Comment by feng-dan** [comment]
![image](https://user-images.githubusercontent.com/29519215/147208205-520fb302-807e-4ee2-aff6-ad188ec59ac2.png)

**Comment by feng-dan** [comment]
![image](https://user-images.githubusercontent.com/29519215/147208482-12742252-d2fe-4b90-80e1-6ae089bdf101.png)

**Comment by feng-dan** [comment]
拦截器正常加载的，可是控制台没有输出日志

**Comment by chentianming11** [comment]
![image](https://user-images.githubusercontent.com/30620547/147209748-786b99ff-8279-4fc1-9cdd-bee7ae2bfce7.png)
可以看看日志打印的代码有没有真正执行，如果执行了的话，那应该跟框架没什么关系了。可能要排查下其他原因了。

**Comment by chentianming11** [comment]
底层就是直接调用了okhttp3的日志打印拦截器

**Comment by feng-dan** [comment]
好的，谢谢了，我看看

**Comment by feng-dan** [comment]
![image](https://user-images.githubusercontent.com/29519215/147211081-8d93b7fc-35aa-43f1-bbcd-5f0701260e8f.png)

**Comment by feng-dan** [comment]
spring-boot.version 2.2.13.RELEASE

**Comment by chentianming11** [comment]
这是http请求调用失败了吧，跟springboot版本没关系的。这个可能需要结合业务、网络针对性进行排查了

**Comment by feng-dan** [comment]
可是 http请求调用 都是正常的，成功返回正常信息

**Comment by feng-dan** [comment]
之前有印象，之前是成功打印请求日志信息的，突然就不行了。

**Comment by feng-dan** [comment]
重新，新环境试试调试一下

**Comment by feng-dan** [comment]
可以了，配置问题
