### ISSUE TITLE
retrofit2.9.0版本retrofit2.Platform的非法反射访问

### ISSUE THREAD

**Issue by sparkzxl** [LianjiaTech/retrofit-spring-boot-starter#93]
控制台输出警告日志
retrofit2.Platform（文件：.m2/maven/repository/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar）对构造函数java.lang.invoke的非法反射访问.MethodHandles$Lookup(java.lang.Class,int)
```text
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/.m2/maven/repository/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by chentianming11** [comment]
这个我没法改啊，是retrofit本身的问题

**Comment by Horrypotter** [comment]
我也刚遇到这个问题了，还没解决吗？

**Comment by chentianming11** [comment]
这个是retrofit的反射调用警告，我这边没法处理。不影响正常使用的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月8日(周二) 下午4:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LianjiaTech/retrofit-spring-boot-starter] retrofit2.9.0版本retrofit2.Platform的非法反射访问 (Issue #93)




 
我也刚遇到这个问题了，还没解决吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
